# =================================================================
# Workflow "TRINH SÁT" - Phiên bản 5.0 - Dùng action chuyên dụng
# =================================================================

name: Explore Custom Source

on:
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-22.04

    steps:
    # Bước 1: Vẫn checkout repo của bạn để lấy các file config
    - name: Checkout local repository
      uses: actions/checkout@v4

    # Bước 2: Dùng action checkout để tải mã nguồn Realtek SDK vào thư mục 'openwrt'
    # Đây là cách làm chuẩn và ổn định nhất.
    - name: Checkout Realtek SDK source code
      uses: actions/checkout@v4
      with:
        repository: 'jekyll2014/rtl819x-sdk-openwrt'
        path: 'openwrt'
        # Chỉ tải nhánh chính và lịch sử gần nhất để tăng tốc
        ref: 'master'
        depth: 1

    - name: Khám phá cấu trúc Target
      run: |
        cd openwrt
        echo "========================================================"
        echo "--- Các thư mục có trong 'target/linux/' ---"
        ls -l target/linux/
        echo "========================================================"
        echo "--- Các file device tree (*.dts) cho realtek ---"
        find target/linux/ -path '*/realtek/dts/*.dts'
        echo "========================================================"
        echo "--- Các file config board (*.c) cho realtek ---"
        find target/linux/ -path '*/realtek/files*/*.c'
        echo "========================================================"

    - name: Dừng lại để xem log
      run: exit 1
