# =================================================================
# Workflow "TRINH SÁT" - Phiên bản 4.0 - Ra lệnh trực tiếp
# =================================================================

name: Explore Custom Source

on:
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Tải mã nguồn Realtek SDK trực tiếp
      run: git clone --depth=1 https://github.com/jekyll2014/rtl819x-sdk-openwrt.git openwrt

    - name: Khám phá cấu trúc Target
      run: |
        cd openwrt
        echo "========================================================"
        echo "--- Các thư mục có trong 'target/linux/' ---"
        ls -l target/linux/
        echo "========================================================"
        echo "--- Các file device tree (*.dts) có thể liên quan ---"
        # Tìm trong toàn bộ mã nguồn xem có dts nào cho rtl96xx không
        find target/linux/ -name "*rtl96*.dts"
        echo "========================================================"

    - name: Dừng lại để xem log
      run: exit 1
