# =================================================================
# Workflow "TRINH SÁT" - Phiên bản 3.0 - Logic mới
# =================================================================

name: Explore Custom Source

on:
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Tải mã nguồn OpenWRT gốc (làm mồi)
      run: git clone --depth=1 https://github.com/openwrt/openwrt.git openwrt

    - name: Thay thế mã nguồn gốc bằng mã nguồn tùy chỉnh
      run: |
        chmod +x diy-part1.sh
        # Chạy script từ thư mục gốc, không cd vào openwrt nữa
        ./diy-part1.sh

    - name: Khám phá cấu trúc Target
      run: |
        cd openwrt
        echo "========================================================"
        echo "--- Các subtarget có sẵn trong target/linux ---"
        ls -l target/linux/
        echo "========================================================"
        echo "--- Các file device tree (*.dts) có sẵn cho realtek ---"
        # Tìm trong toàn bộ mã nguồn xem có thư mục target nào tên là 'realtek' không
        find target/linux/ -name "realtek" -type d -exec find {} -name "*.dts" \;
        echo "========================================================"

    - name: Dừng lại để xem log
      run: exit 1
