# =================================================================
# Workflow "TRINH SÁT" - Phiên bản 6.0 - Nguồn SDK mới
# =================================================================

name: Explore New Realtek Source

on:
  workflow_dispatch:

jobs:
  explore:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout local repository
      uses: actions/checkout@v4

    - name: Tải mã nguồn Realtek SDK (Nguồn mới)
      uses: actions/checkout@v4
      with:
        repository: 'a7621a/Realtek-OPENWRT-19.07.8-ETERNITY'
        path: 'openwrt'
        ref: 'master'
        fetch-depth: 1 # Sửa lỗi "depth" thành "fetch-depth" cho đúng chuẩn

    - name: Khám phá cấu trúc Target
      run: |
        cd openwrt
        echo "========================================================"
        echo "--- Các thư mục có trong 'target/linux/' ---"
        ls -l target/linux/
        echo "========================================================"
        echo "--- Tìm kiếm các file dts liên quan đến 'rtl' ---"
        find target/linux/ -name "*rtl*.dts"
        echo "========================================================"

    - name: Dừng lại để xem log
      run: exit 1
